### PR TITLE
Chore: upgrade to go1.21 and a little tidy-up

### PR DESCRIPTION
**Pull request by ikari-pl**
* Switches from `go1.19` to `go1.21`
* Moves away from deprecated `ioutil` to `io` and `fs`
* renames `makefile` and `readme.md` to `Makefile` and `README.md` (customary names)
* lists `.PHONY` targets in Makefile (ones that do not produce files names as the targets)
* moves `.DEFAULT_GOAL` to top, for visibility
* parses out module name for govulcheck from `go.mod`, in case I rename my fork ;-)
* update the few dependencies slightly

### CODE REVIEW

**Comment by jeromelesaux** [comment]
Tanks for you work.

**Comment by jeromelesaux** [comment]
May you make a git rebase from the main branch ?

**Comment by ikari-pl** [comment]
> May you make a git rebase from the main branch ?

I can, of course. Or, if you'd like, you can enable "squash & merge" - I tried to name the changes separately so in the end they would make more sense in the blame/annotations.

I am continuing to update it a little - renaming some things to a bit more standard ways to name them, translated comments to English, and will proceed from there to trying to redo how arguments are handled (into more command and options structure in a little more separated flows), will add more tests (before I break anything), and make them use assertions more :D 

Are you interested in those changes too, or should I keep them within my fork? (:

**Comment by ikari-pl** [comment]
I love these CPC-related projects btw :) and makes me personally happy to combine Golang and some retro :)

**Comment by ikari-pl** [comment]
Decided to replace this PR with squashed #8 per request, so I can move on with my main branch

**Pull request closed without merging**
